// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDvxbB9Wq5CyG5Pd31sf4TcCGkOh3sAg',
    appId: '1:900253986862:android:30bd4c0210b71d4eb6efbf',
    messagingSenderId: '900253986862',
    projectId: 'fcsocialfitness',
    databaseURL: 'https://fcsocialfitness-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fcsocialfitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfG_Kqz43UcoqeJxzADmpLidFVSwNWl1Q',
    appId: '1:900253986862:ios:8a02f2499d9fac35b6efbf',
    messagingSenderId: '900253986862',
    projectId: 'fcsocialfitness',
    databaseURL: 'https://fcsocialfitness-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fcsocialfitness.appspot.com',
    iosClientId: '900253986862-7gg9faqpmeglnsldu7sbjr07qcvtoltf.apps.googleusercontent.com',
    iosBundleId: 'it.codeloops.fcsocialfitness',
  );
}
