// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOYhILhtsopD-U2446RO4tGey0M1z7QNw',
    appId: '1:284859984937:web:c3a68ffb409dca97d78038',
    messagingSenderId: '284859984937',
    projectId: 'instagramclone-3696b',
    authDomain: 'instagramclone-3696b.firebaseapp.com',
    databaseURL: 'https://instagramclone-3696b-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclone-3696b.appspot.com',
    measurementId: 'G-PCVG2M32H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqldYT4NDl3r-ifoJ3zv0cD0zSMSTSpQ',
    appId: '1:284859984937:android:f759321b300d5422d78038',
    messagingSenderId: '284859984937',
    projectId: 'instagramclone-3696b',
    databaseURL: 'https://instagramclone-3696b-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclone-3696b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL3uAuM65n0BxejnBkfPqhkqQB9e_GbaQ',
    appId: '1:284859984937:ios:6b783099b1891a12d78038',
    messagingSenderId: '284859984937',
    projectId: 'instagramclone-3696b',
    databaseURL: 'https://instagramclone-3696b-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclone-3696b.appspot.com',
    iosClientId: '284859984937-0do22a472gg4b6rstq3l5560oqtsiod5.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL3uAuM65n0BxejnBkfPqhkqQB9e_GbaQ',
    appId: '1:284859984937:ios:6b783099b1891a12d78038',
    messagingSenderId: '284859984937',
    projectId: 'instagramclone-3696b',
    databaseURL: 'https://instagramclone-3696b-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclone-3696b.appspot.com',
    iosClientId: '284859984937-0do22a472gg4b6rstq3l5560oqtsiod5.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
